# Docker Compose for rreading-glasses using Goodreads

services:
  rreading-glasses:
    depends_on:
      rreading-glasses-db:
        condition: service_started  
    image: blampe/rreading-glasses:latest
    container_name: rreading-glasses
    hostname: rreading-glasses
    entrypoint: ["/main", "serve"]
    command:    
      - --upstream=www.goodreads.com
      - --postgres-host=rreading-glasses-db
      - --postgres-database=rreading-glasses
      - --postgres-user=rreading-glasses
      - --postgres-password= # Generate a random string without special symbols
      - --cookie= # Your GR cookie. Only used for GR.
      - --verbose
    restart: always
    ports:
      - "8788:8788"

  rreading-glasses-db:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: rreading-glasses
      POSTGRES_PASSWORD:  # Generated password from above
      POSTGRES_DB: rreading-glasses
    ports:
      - "5432:5432"
    volumes:
      - rreading_glasses_data:/var/lib/postgresql/data

volumes:
  rreading_glasses_data:
